{
 "title": "Quarkus Metrics",
 "description": "Generic dashboard for Quarkus apps",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(base_jvm_uptime_seconds, namespace)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(base_jvm_uptime_seconds{namespace=\"$namespace\"}, service)"
   },
   {
    "name": "env",
    "label": "Environment",
    "query": "label_values(base_jvm_uptime_seconds{namespace=\"$namespace\", service=\"$service\"}, env)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(base_jvm_uptime_seconds{namespace=\"$namespace\", service=\"$service\", env=\"$env\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Quick Facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "base_jvm_uptime_seconds{pod=\"$instance\"}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "gauge",
     "description": "Usage for the JVM process. 100% means that all CPUs were actively running threads from the JVM",
     "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "base_cpu_processCpuLoad_percent{pod=\"$instance\"}",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Mem",
     "type": "gauge",
     "description": "Used / max heap memory",
     "gridPos": { "h": 3, "w": 2, "x": 5, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "base_memory_usedHeap_bytes{pod=\"$instance\"}*100/base_memory_maxHeap_bytes{pod=\"$instance\"}",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Database connections",
     "type": "bargauge",
     "description": "Add this to your application.properties first:\nquarkus.datasource.metrics.enabled=true",
     "gridPos": { "h": 3, "w": 4, "x": 7, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vendor_agroal_active_count{pod=\"$instance\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "vendor_agroal_available_count{pod=\"$instance\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "vendor_agroal_max_used_count{pod=\"$instance\"}",
       "legendFormat": "Max"
      },
      {
       "expr": "vendor_agroal_leak_detection_count_total{pod=\"$instance\"}",
       "legendFormat": "Leaks"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP (all instances aggregated)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request count over last [5m] ",
     "type": "graph",
     "description": "Add this to your application.properties first:\nquarkus.resteasy.metrics.enabled=true",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(application_http_request_total{namespace=\"$namespace\", service=\"$service\", env=\"$env\"}[5m])) by (method, endpoint)",
       "legendFormat": "{{method}} {{endpoint}}"
      }
     ]
    },
    {
     "title": "Response times over last [5m]",
     "type": "graph",
     "description": "Add this to your application.properties first:\nquarkus.resteasy.metrics.enabled=true",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(application_http_request_elapsedTime_seconds{namespace=\"$namespace\", service=\"$service\", env=\"$env\"}[5m]) / rate(application_http_request_total{namespace=\"$namespace\", service=\"$service\", env=\"$env\"}[5m])) by (method, endpoint)",
       "legendFormat": "Average {{method}} {{endpoint}}"
      },
      {
       "expr": "max(rate(application_http_request_elapsedTime_seconds{namespace=\"$namespace\", service=\"$service\", env=\"$env\"}[5m]) / rate(application_http_request_total{namespace=\"$namespace\", service=\"$service\", env=\"$env\"}[5m])) > 0",
       "legendFormat": "Max of all requests"
      },
      {
       "expr": "avg(rate(base_REST_request_elapsedTime_seconds{namespace=\"$namespace\", service=\"$service\", env=\"$env\"}[5m]) / rate(base_REST_request_total{namespace=\"$namespace\", service=\"$service\", env=\"$env\"}[5m])) by (method, endpoint)",
       "legendFormat": "Average {{class}} {{method}}"
      },
      {
       "expr": "max(rate(base_REST_request_elapsedTime_seconds{namespace=\"$namespace\", service=\"$service\", env=\"$env\"}[5m]) / rate(base_REST_request_total{namespace=\"$namespace\", service=\"$service\", env=\"$env\"}[5m])) > 0",
       "legendFormat": "Max of all requests"
      }
     ]
    },
    {
     "title": "Http errors (4XX & 5XX) last minute",
     "type": "graph",
     "description": "You need quarkus-rfc7807-problem-extension dependency + quarkus.rfc7807-problem.metrics.enabled=true setting in application.properties",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "increase(application_http_error_total{namespace=\"$namespace\", service=\"$service\", env=\"$env\", status=~\"5.*\"}[1m])",
       "legendFormat": "HTTP {{status}}"
      },
      {
       "expr": "increase(application_http_error_total{namespace=\"$namespace\", service=\"$service\", env=\"$env\", status=~\"4.*\"}[1m])",
       "legendFormat": "HTTP {{status}}"
      }
     ]
    }
   ]
  },
  { "title": "Hardware utilisation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Displays  the \"recent cpu usage\" for the Java Virtual Machine process. This value is a double in the [0.0,1.0] interval. A value of 0.0 means that none of the CPUs were running threads from the JVM process during the recent period of time observed, while a value of 1.0 means that all CPUs were actively running threads from the JVM 100% of the time during the recent period being observed. Threads from the JVM include the application threads as well as the JVM internal threads. All values betweens 0.0 and 1.0 are possible depending of the activities going on in the JVM process and the whole system. If the Java Virtual Machine recent CPU usage is not available, the method returns a negative value.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad_percent{pod=\"$instance\"}",
     "legendFormat": "Usage for the JVM process. 100% means that all CPUs were actively running threads from the JVM"
    },
    {
     "expr": "avg_over_time(base_cpu_processCpuLoad_percent{pod=\"$instance\"}[1h])",
     "legendFormat": "Usage for the JVM process - last hour average"
    },
    {
     "expr": "vendor_cpu_systemCpuLoad_percent{pod=\"$instance\"}",
     "legendFormat": "Usage for the whole system. 100% means that all CPUs were actively running 100% of the time"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "description": "The system load average is the sum of the number of runnable entities queued to the available processors and the number of runnable entities running on the available processors averaged over a period of time. The way in which the load average is calculated is operating system specific but is typically a damped time-dependent average. If the load average is not available, a negative value is displayed. This attribute is designed to provide a hint about the system load and may be queried frequently. The load average may be unavailable on some platforms where it is expensive to implement this method.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_cpu_systemLoadAverage{pod=\"$instance\"}",
     "legendFormat": "System load average for the last minute"
    },
    {
     "expr": "base_cpu_availableProcessors{pod=\"$instance\"}",
     "legendFormat": "Number of processors available to the JVM"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_thread_count{pod=\"$instance\"}-base_thread_daemon_count{pod=\"$instance\"}",
     "legendFormat": "Live threads"
    },
    {
     "expr": "base_thread_daemon_count{pod=\"$instance\"}",
     "legendFormat": "Live daemon threads"
    },
    {
     "expr": "base_thread_count{pod=\"$instance\"}",
     "legendFormat": "Live threads total"
    },
    {
     "expr": "base_thread_max_count{pod=\"$instance\"}",
     "legendFormat": "Peak live threads total"
    }
   ]
  },
  {
   "title": "Container Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_maxHeap_bytes{pod=\"$instance\"}",
     "legendFormat": "Max heap"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=\"$instance\"})",
     "legendFormat": "Container working set"
    },
    {
     "expr": "vendor_memory_freeSwapSize_bytes{pod=\"$instance\"}",
     "legendFormat": "Free swap space"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{pod=\"$instance\"}",
     "legendFormat": "Container limit"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Heap",
   "type": "graph",
   "description": "Java objects reside in an area called the heap. The heap is created when the JVM starts up and may increase or decrease in size while the application runs. When the heap becomes full, garbage is collected. During the garbage collection objects that are no longer used are cleared, thus making space for new objects.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{pod=\"$instance\"}",
     "legendFormat": "Used heap memory"
    },
    {
     "expr": "base_memory_committedHeap_bytes{pod=\"$instance\"}",
     "legendFormat": "Memory committed (guaranteed) for the JVM to use"
    },
    {
     "expr": "base_memory_maxHeap_bytes{pod=\"$instance\"}",
     "legendFormat": "Maximum amount (not guaranteed) of heap memory that can be used for memory management"
    }
   ]
  },
  {
   "title": "Heap Memory Pools",
   "type": "graph",
   "description": "Memory Pools are created by JVM memory managers to create a pool of immutable objects. Memory Pool can belong to Heap or Perm Gen, depending on JVM memory manager implementation.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
   "repeat": "jvm_memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memoryPool_usage_bytes{pod=\"$instance\"}",
     "legendFormat": "Usage {{name}}"
    },
    {
     "expr": "vendor_memoryPool_usage_max_bytes{pod=\"$instance\"}",
     "legendFormat": "Max {{name}}"
    }
   ]
  },
  {
   "title": "Non-Heap",
   "type": "graph",
   "description": "The JVM has memory other than the heap, referred to as Non-Heap Memory. It is created at the JVM startup and stores per-class structures such as runtime constant pool, field and method data, and the code for methods and constructors, as well as interned Strings. The default maximum size of non-heap memory is 64 MB.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(vendor_memory_usedNonHeap_bytes{pod=\"$instance\"})",
     "legendFormat": "Used non-heap memory"
    },
    {
     "expr": "sum(vendor_memory_committedNonHeap_bytes{pod=\"$instance\"})",
     "legendFormat": "Non heap memory committed (guaranteed) for the JVM to use"
    },
    {
     "expr": "sum(vendor_memory_maxNonHeap_bytes{pod=\"$instance\"})",
     "legendFormat": "Maximum amount of used non-heap memory"
    }
   ]
  },
  {
   "title": "Class Loader",
   "type": "graph",
   "description": "Class loaders are responsible for loading Java classes during runtime dynamically to the JVM (Java Virtual Machine). Also, they are part of the JRE (Java Runtime Environment). Hence, the JVM doesn't need to know about the underlying files or file systems in order to run Java programs thanks to class loaders.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_classloader_loadedClasses_count{pod=\"$instance\"}",
     "legendFormat": "Classes currently loaded in the JVM"
    },
    {
     "expr": "delta(base_classloader_loadedClasses_count{pod=\"$instance\"}[1m])",
     "legendFormat": "Classes currently loaded in the JVM - delta 1m"
    }
   ]
  },
  {
   "title": "Datasource (Agroal)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection pool",
     "type": "graph",
     "description": "Add this to your application.properties first:\nquarkus.datasource.metrics.enabled=true",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(vendor_agroal_acquire_count_total{pod=\"$instance\"}[1m])",
       "legendFormat": "Acquire operation per second"
      },
      {
       "expr": "vendor_agroal_active_count{pod=\"$instance\"}",
       "legendFormat": "Active connections"
      },
      {
       "expr": "vendor_agroal_available_count{pod=\"$instance\"}",
       "legendFormat": "Idle connections, available to be acquired"
      },
      {
       "expr": "increase(vendor_agroal_creation_count_total{pod=\"$instance\"}[1m])",
       "legendFormat": "Created connections in the last minute"
      },
      {
       "expr": "increase(vendor_agroal_destroy_count_total{pod=\"$instance\"}[1m])",
       "legendFormat": "Destroyed connections last minute"
      },
      {
       "expr": "vendor_agroal_max_used_count{pod=\"$instance\"}",
       "legendFormat": "Maximum number of connections active simultaneously"
      },
      {
       "expr": "increase(vendor_agroal_leak_detection_count_total{pod=\"$instance\"}[1m])",
       "legendFormat": "Leak detections"
      }
     ]
    },
    {
     "title": "Timing",
     "type": "graph",
     "description": "Add this to your application.properties first:\nquarkus.datasource.metrics.enabled=true",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(vendor_agroal_blocking_time_total_seconds{pod=\"$instance\"}[1m])*1000",
       "legendFormat": "Time to acquire a connection"
      },
      {
       "expr": "rate(vendor_agroal_creation_time_total_seconds{pod=\"$instance\"}[1m])*1000",
       "legendFormat": "Time to create a connection"
      }
     ]
    },
    {
     "title": "Stats since restart",
     "type": "stat",
     "description": "Add this to your application.properties first:\nquarkus.datasource.metrics.enabled=true",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "vendor_agroal_blocking_time_max_seconds{pod=\"$instance\"}*1000",
       "legendFormat": "Max waiting time to acquire a connection"
      },
      {
       "expr": "vendor_agroal_blocking_time_average_seconds{pod=\"$instance\"}*1000",
       "legendFormat": "Average waiting time to acquire a connection"
      },
      {
       "expr": "vendor_agroal_creation_time_max_seconds{pod=\"$instance\"}*1000",
       "legendFormat": "Max time for a connection to be created"
      },
      {
       "expr": "vendor_agroal_creation_time_average_seconds{pod=\"$instance\"}*1000",
       "legendFormat": "Average time for a connection to be created"
      },
      {
       "expr": "vendor_agroal_leak_detection_count_total{pod=\"$instance\"}",
       "legendFormat": "Connection leaks detected"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collections in last minute",
     "type": "graph",
     "description": "JVM garbage collectors summary:\nhttps://www.baeldung.com/jvm-garbage-collectors",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "increase(base_gc_total{pod=\"$instance\"}[1m])",
       "legendFormat": "Number of collections that have occurred last minute ({{name}})"
      }
     ]
    },
    {
     "title": "Durations in last minute",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "increase(base_gc_time_total_seconds{pod=\"$instance\"}[1m])",
       "legendFormat": "Approximate accumulated collection elapsed time ({{name}})"
      }
     ]
    }
   ]
  }
 ]
}